Repository pluralsh/design-system, pull requests merged in 2022-11, with the labels that each got.

#241 Add CodeQL action
  .github/workflows/codeql.yml
Labels: enhancement

#283 feat: Design system maintenance updates
  package.json
  src/components/Alert.tsx
  src/components/Chip.tsx
  src/components/InstalledLabel.tsx
  src/components/ProgressBar.tsx
  src/components/Tag.tsx
  src/components/UserCard.tsx
  src/index.ts
  src/stories/Alert.stories.tsx
  src/stories/DropdownButton.stories.tsx
  src/stories/InstalledLabel.stories.tsx
  src/stories/Tag.stories.tsx
  src/stories/UserCard.stories.tsx
  src/theme/text.ts
Labels: enhancement

#291 Update deps
  package.json
  yarn.lock
Labels: dependencies

#296 ci: Migrate to ViteJS as the storybook bundler
  .github/workflows/ci.yml
  .storybook/main.js
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  .storybook/theme.ts
  package.json
  src/components/ValidatedInput.tsx
  yarn.lock
Labels: dependencies

#323 feat: Add honorable-recipe-mapper
  package.json
  src/theme.tsx
  yarn.lock
Labels: dependencies

#334 feat: DS maintenance
  package.json
  src/components/Logo.tsx
  src/components/Sidecar.tsx
  src/stories/Logo.stories.tsx
  yarn.lock
Labels: enhancement

#361 fix(build): Reconfigure vite as per official migration guide and fix firebase deploy
  .eslintignore
  .eslintrc.js
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.ts
  .storybook/theme.ts
  firebase.json
  index.html
  package.json
  tsconfig.eslint.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: bug
