Repository pluralsh/design-system, pull requests merged in 2023-10, with the labels that each got.

#525 feat: add support for disabled prop to SubTab
  src/components/SubTab.tsx
  src/components/TabList.tsx
  src/stories/Tab.stories.tsx
Labels: enhancement

#526 feat: Stepper and Select improvements
  .eslintrc.cjs
  package.json
  scripts/makeIcon.js
  src/ThemeDecorator.tsx
  src/components/Accordion.tsx
  src/components/IconFrame.tsx
  src/components/InfoPanel.tsx
  src/components/Select.tsx
  src/components/Stepper.tsx
  src/stories/Markdown.stories.tsx
  src/stories/Select.stories.tsx
  src/stories/Stepper.stories.tsx
  src/stories/Table.stories.tsx
  src/stories/Toast.stories.tsx
  src/stories/Wizard.stories.tsx
  src/types/styled.d.ts
  yarn.lock
Labels: bug, enhancement

#530 feat: Modal and Input improvements
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/Modal.tsx
  src/stories/Input.stories.tsx
  src/stories/Modal.stories.tsx
  src/theme.tsx
Labels: bug, enhancement

#531 fix: Combobox padding
  src/components/Chip.tsx
  src/components/ComboBox.tsx
  src/components/Input.tsx
  src/components/Spinner.tsx
  src/stories/ComboBox.stories.tsx
Labels: bug

#532 fix: Export Spinner component
  src/components/Card.tsx
  src/components/Modal.tsx
  src/index.ts
Labels: bug
