Repository pluralsh/design-system, pull requests merged in 2024-03, with the labels that each got.

#574 feat: Add Megaphone and MS Teams icons for Notifications views
  src/components/icons/MegaphoneIcon.tsx
  src/components/icons/MsTeamsLogoIcon.tsx
  src/icons.ts
Labels: enhancement, design

#575 fix: Parts of elements appear above the Modal actions area when scrolling
  src/components/Modal.tsx
  src/stories/Modal.stories.tsx
Labels: bug, design

#576 feat: allow tablist to be scrollable
  src/components/TabList.tsx
  src/stories/TabList.stories.tsx
Labels: enhancement

#579 feat: add conditional onClick action to chip list
  src/components/ChipList.tsx
  src/stories/ChipList.stories.tsx
Labels: enhancement
