Repository pluralsh/design-system, pull requests merged in 2024-10, with the labels that each got.

#648 feat: Reduce spacing between icons in sidebar and add vertical padding
  src/components/Menu.tsx
  src/components/MenuItem.tsx
  src/components/SidebarItem.tsx
  src/components/SidebarSection.tsx
  src/index.ts
Labels: enhancement

#650 feat: upgrade to styled components v6
  package.json
  src/components/AppIcon.tsx
  src/components/ArrowScroll.tsx
  src/components/Banner.tsx
  src/components/Card.tsx
  src/components/Checkbox.tsx
  src/components/ChecklistItem.tsx
  src/components/Chip.tsx
  src/components/Code.tsx
  src/components/ComboBox.tsx
  src/components/DateField.tsx
  src/components/Flyover.tsx
  src/components/IconFrame.tsx
  src/components/InlineCode.tsx
  src/components/Input2.tsx
  src/components/Layer.tsx
  src/components/LightDarkSwitch.tsx
  src/components/ListBoxItem.tsx
  src/components/LoadingSpinner.tsx
  src/components/Markdown.tsx
  src/components/Modal.tsx
  src/components/Radio.tsx
  src/components/Select.tsx
  src/components/Sidebar.tsx
  src/components/SidebarExpandWrapper.tsx
  src/components/SidebarItem.tsx
  src/components/SidebarSection.tsx
  src/components/Spinner.tsx
  src/components/SubTab.tsx
  src/components/Switch.tsx
  src/components/TabList.tsx
  src/components/TabPanel.tsx
  src/components/Table.tsx
  src/components/TagMultiSelect.tsx
  src/components/TextSwitch.tsx
  src/components/TreeNavigation.tsx
  src/components/contexts/BreadcrumbsContext.tsx
  src/components/icons/FastReverseIcon.tsx
  src/components/icons/ThumbsDownIcon.tsx
  src/icons.ts
  src/markdoc/components/Figure.tsx
  src/markdoc/components/List.tsx
  src/stories/ClusterTagsTemplate.tsx
  src/stories/CodeEditor.stories.tsx
  src/stories/Select.stories.tsx
  src/stories/Stepper.stories.tsx
  src/stories/Table.stories.tsx
  src/stories/TextSwitch.stories.tsx
  src/stories/_SemanticSystem.stories.tsx
  src/theme.tsx
  yarn.lock
Labels: enhancement, dependencies

#652 fix: remove deprecated pricing calculator
  package.json
  src/components/pricingcalculator/PricingCalculator.tsx
  src/components/pricingcalculator/PricingCalculatorExtended.tsx
  src/components/pricingcalculator/controls/AppsControl.tsx
  src/components/pricingcalculator/controls/ClustersControl.tsx
  src/components/pricingcalculator/controls/Control.tsx
  src/components/pricingcalculator/controls/ProvidersControl.tsx
  src/components/pricingcalculator/controls/UsersControl.tsx
  src/components/pricingcalculator/costs/Cost.tsx
  src/components/pricingcalculator/costs/Costs.tsx
  src/components/pricingcalculator/costs/TotalCost.tsx
  src/components/pricingcalculator/misc.tsx
  src/index.ts
  src/markdoc/tags/calculator.markdoc.ts
  src/markdoc/tags/index.ts
  src/stories/PricingCalculator.stories.tsx
  src/stories/PricingCalculatorExtended.stories.tsx
  yarn.lock
Labels: bug

#653 fix: treenav issue
  src/components/ComboBox.tsx
  src/components/TreeNavigation.tsx
Labels: bug

#655 fix: broken toast
  src/components/Layer.tsx
Labels: bug

#656 fix: revert incorrect transient props
  src/components/Select.tsx
  src/components/TabList.tsx
  src/components/TagMultiSelect.tsx
Labels: bug

#660 feat: add new icons for ai chat
  src/components/icons/ChatFilledIcon.tsx
  src/components/icons/ChatOutlineIcon.tsx
  src/components/icons/PushPinFilledIcon.tsx
  src/components/icons/PushPinOutlineIcon.tsx
  src/components/icons/ShrinkIcon.tsx
  src/icons.ts
Labels: enhancement
